Supermarketsystem/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Supermarketsystem.Areas.Admin.Models;
using Supermarketsystem.BAL;
using System.Security.Cryptography.Xml;

namespace Supermarketsystem.Areas.Admin.Controllers
{
    [CheckAccess]
    [Area("Admin")]
    [Route("Admin/{Controller}/{Action}")]

    public class CategoryController : Controller
    {
        Uri baseuri = new Uri("http://localhost:5071/api");
        private readonly HttpClient _Client;
        public CategoryController() { 
            _Client = new HttpClient();
            _Client.BaseAddress = baseuri;
        }
        public IActionResult GET()
        {
            List<CategoryModel> categories = new List<CategoryModel>();
            HttpResponseMessage response = _Client.GetAsync($"{_Client.BaseAddress}/Category/Get").Result;
            if (response.IsSuccessStatusCode) { 
            
                string data = response.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                categories = JsonConvert.DeserializeObject<List<CategoryModel>>(extractedDtaJson);
            }
            return View("CategoryList",categories);
        }


        public IActionResult Delete(int CategoryID)
        {
            HttpResponseMessage response = _Client.DeleteAsync($"{_Client.BaseAddress}/Category/Delete?CategoryID={CategoryID}").Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["Message"] = "Person Delete";
            }
            else
            {
                TempData["Message"] = "Error deleting person. Please try again.";
            }

            return RedirectToAction("GET");

        }

        [HttpGet]
        public IActionResult Edit(int CategoryID) { 
        CategoryModel category = new CategoryModel();
            HttpResponseMessage response = _Client.GetAsync($"{_Client.BaseAddress}/Category/GetById/{CategoryID}").Result;
            if (response.IsSuccessStatusCode)
            {

                string data = response.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                category = JsonConvert.DeserializeObject<CategoryModel>(extractedDtaJson);
            }
            return View("CategoryAdd",category);
               
        }

        [HttpPost]
        public async Task<IActionResult> Save(CategoryModel categoryModel)
        {
            try
            {
                MultipartFormDataContent fromdata = new MultipartFormDataContent();
                fromdata.Add(new StringContent(categoryModel.CategoryName), "CategoryName");
                fromdata.Add(new StringContent(categoryModel.CategoryDescription), "CategoryDescription");
                if (categoryModel.CategoryID == 0)
                {
                    HttpResponseMessage response = await _Client.PostAsync($"{_Client.BaseAddress}/Category/Post", fromdata);
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["Message"] = "Person Inserted";
                        return RedirectToAction("GET");
                    }
                }
                else
                {
                    HttpResponseMessage response = await _Client.PutAsync($"{_Client.BaseAddress}/Category/Put?CategoryID={categoryModel.CategoryID}", fromdata);
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["Message"] = "Person updated";
                        return RedirectToAction("GET");
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An Error Occured" + ex.Message;
            }
            return RedirectToAction("GET");
        }



        public IActionResult Export()
        {
            try
            {
                HttpResponseMessage response = _Client.GetAsync($"{_Client.BaseAddress}/Category/CategoryExport").Result;

                if (response.IsSuccessStatusCode)
                {
                    // Read the response content as a byte array
                    byte[] pdfBytes = response.Content.ReadAsByteArrayAsync().Result;

                    // Return the PDF file
                    return File(pdfBytes, "application/pdf", "user_data.pdf");
                }
                else
                {
                    // Handle unsuccessful response here
                    if (response.Content != null)
                    {
                        string responseContent = response.Content.ReadAsStringAsync().Result;
                        return Content($"Failed to export PDF. Server returned: {responseContent}");
                    }
                    else
                    {
                        return NotFound("No data available to export.");
                    }
                }
            }
            catch (HttpRequestException ex)
            {
                // Handle HTTP request errors
                return StatusCode(500, $"Failed to export PDF. HTTP request error: {ex.Message}");
            }
            catch (Exception ex)
            {
                // Handle other exceptions
                return StatusCode(500, $"An error occurred: {ex.Message}");
            }
        }

        private byte[] GeneratePdf(List<CategoryModel> persons)
        {
            // Your PDF generation logic here
            // Replace the following placeholder code with your actual PDF generation logic

            using (MemoryStream ms = new MemoryStream())
            {
                // Placeholder: write some PDF content to the memory stream
                // For example:
                var pdfContent = "PDF Content goes here";
                var pdfBytes = System.Text.Encoding.UTF8.GetBytes(pdfContent);
                ms.Write(pdfBytes, 0, pdfBytes.Length);
                return ms.ToArray();
            }
        }

    }
}

Supermarketsystem/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Supermarketsystem.Areas.Admin.Models;
using Supermarketsystem.BAL;

namespace Supermarketsystem.Areas.Admin.Controllers
{
    [CheckAccess]
    [Area("Admin")]
    [Route("Admin/{Controller}/{Action}")]
    public class DashboardController : Controller
    {
        Uri baseuri = new Uri("http://localhost:5071/api");
        private readonly HttpClient _Client;
        public DashboardController()
        {
            _Client = new HttpClient();
            _Client.BaseAddress = baseuri;
        }
        public IActionResult GET()
        {
            List<DashboardModel> dashboards = new List<DashboardModel>();
            HttpResponseMessage response = _Client.GetAsync($"{_Client.BaseAddress}/Dashboard/Get").Result;
            if (response.IsSuccessStatusCode)
            {

                string data = response.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                dashboards = JsonConvert.DeserializeObject<List<DashboardModel>>(extractedDtaJson);
            }
      

            return View("DashboardList",dashboards);
        }
    }
}

Supermarketsystem/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using Supermarketsystem.Areas.Admin.Models;
using Supermarketsystem.BAL;

namespace Supermarketsystem.Areas.Admin.Controllers
{
    [CheckAccess]
    [Area("Admin")]
    [Route("Admin/{Controller}/{Action}")]
    public class ProductController : Controller
    {
        Uri baseuri = new Uri("http://localhost:5071/api");
        private readonly HttpClient _Client;
        public ProductController()
        {
            _Client = new HttpClient();
            _Client.BaseAddress = baseuri;
        }
        public IActionResult GET()
        {
            List<ProductModel> products = new List<ProductModel>();
            HttpResponseMessage response = _Client.GetAsync($"{_Client.BaseAddress}/Product/Get").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                products = JsonConvert.DeserializeObject<List<ProductModel>>(extractedDtaJson);
            }
            return View("ProductList", products);
        }

        public IActionResult Delete(int ProductID)
        {
            HttpResponseMessage response = _Client.DeleteAsync($"{_Client.BaseAddress}/Product/Delete?ProductID={ProductID}").Result;
            if (response.IsSuccessStatusCode)
            {
                TempData["Message"] = "Person Delete";
            }
            else
            {
                TempData["Message"] = "Error deleting person. Please try again.";
            }

            return RedirectToAction("GET");

        }


      
        public IActionResult GetCascading(int CategoryID)
        {
            List<SubcategoryDropDown> productModel = new List<SubcategoryDropDown>();
            HttpResponseMessage response = _Client.GetAsync($"{_Client.BaseAddress}/Product/Cascading/{CategoryID}").Result;
            if (response.IsSuccessStatusCode)
            {

                string data = response.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                productModel = JsonConvert.DeserializeObject<List<SubcategoryDropDown>>(extractedDtaJson);

               
               
            }

           var product= productModel;
            return Json(product);
        }


        [HttpGet]
        public IActionResult Edit(int ProductID)
        {



            /* Dropdown start*/
            List<Categorydropdown> Dropdown = new List<Categorydropdown>();
            HttpResponseMessage response1 = _Client.GetAsync($"{_Client.BaseAddress}/Product/GetCategoryDropdown").Result;
            if (response1.IsSuccessStatusCode)
            {

                string data = response1.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                Dropdown = JsonConvert.DeserializeObject<List<Categorydropdown>>(extractedDtaJson);
                ViewBag.DropDown = Dropdown;

            }


            /*Dropdown end*/


            /*Dropdown start*/
            List<SubcategoryDropDown> subcategoryDropDowns = new List<SubcategoryDropDown>();
            HttpResponseMessage response2 = _Client.GetAsync($"{_Client.BaseAddress}/Product/GetSubCategoryDropdown").Result;
            if (response2.IsSuccessStatusCode)
            {

                string data = response2.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                subcategoryDropDowns = JsonConvert.DeserializeObject<List<SubcategoryDropDown>>(extractedDtaJson);
                ViewBag.SubcategoryDropDown = subcategoryDropDowns;
            }

            /* Dropdown end*/




            ProductModel productModel = new ProductModel();
            HttpResponseMessage response = _Client.GetAsync($"{_Client.BaseAddress}/Product/GetById/{ProductID}").Result;
            if (response.IsSuccessStatusCode)
            {

                string data = response.Content.ReadAsStringAsync().Result;
                dynamic jsonobject = JsonConvert.DeserializeObject(data);
                var dataofobject = jsonobject.data;
                var extractedDtaJson = JsonConvert.SerializeObject(dataofobject, Formatting.Indented);
                productModel = JsonConvert.DeserializeObject<ProductModel>(extractedDtaJson);



            }
            return View("ProductAdd", productModel);
        }



    


[HttpPost]
        public async Task<IActionResult> Save(ProductModel productModel)
        {
            try
            {
                MultipartFormDataContent fromdata = new MultipartFormDataContent();
                fromdata.Add(new StringContent(Convert.ToString(productModel.CategoryID)), "CategoryID");
                fromdata.Add(new StringContent(Convert.ToString(productModel.SubCategoryID)), "SubCategoryID");
                fromdata.Add(new StringContent(productModel.ProductName), "ProductName");
                fromdata.Add(new StringContent(Convert.ToString(productModel.ProductQuantity)), "ProductQuantity");
                fromdata.Add(new StringContent(Convert.ToString(productModel.ProductPrice)), "ProductPrice");
                fromdata.Add(new StringContent(Convert.ToString(productModel.ProductExpiryDate)), "ProductExpiryDate");
                fromdata.Add(new StringContent(productModel.ProductImage), "ProductImage");
                
                if (productModel.ProductID == 0)
                {
                    HttpResponseMessage response = await _Client.PostAsync($"{_Client.BaseAddress}/Product/Post", fromdata);
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["Message"] = "Person Inserted";
                        return RedirectToAction("GET");
                    }
                }
                else
                {
                    HttpResponseMessage response = await _Client.PutAsync($"{_Client.BaseAddress}/Product/Put?ProductID={productModel.ProductID}", fromdata);
                    if (response.IsSuccessStatusCode)
                    {
                        TempData["Message"] = "Person updated";
                        return RedirectToAction("GET");
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An Error Occured" + ex.Message;
            }
            return RedirectToAction("GET");
        }

    }
}

Supermarketsystem/Areas/Admin/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using Supermarketsystem.Areas.Login.Models;
using Supermarketsystem.BAL;
using System.Reflection;

namespace Supermarketsystem.Areas.Admin.Controllers
{
    [CheckAccess]
    [Area("Admin")]
    [Route("Admin/{Controller}/{Action}")]
    public class ProfileController : Controller
    {
        public IActionResult GET()
        {
            //string firstName = HttpContext.Session.GetString("FirstName");
            string firstName = HttpContext.Session.GetString("FirstName");
            string lastName = HttpContext.Session.GetString("LastName");
            string email = HttpContext.Session.GetString("Email");
            string username = HttpContext.Session.GetString("UserName");
            ViewData["firstName"] = firstName;
            ViewData["lastName"] = lastName;
            ViewData["email"] = email;
            ViewData["username"] = username;
            return View("ProfileList");
        }
    }
}

Supermarketsystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<title>@ViewData["Title"] - Supermarketsystem</title>*@
    <meta name="description" content="Vali is a responsive and free admin theme built with Bootstrap 4, SASS and PUG.js. It's fully customizable and modular.">
    <!-- Twitter meta-->
    <meta property="twitter:card" content="summary_large_image">
    
    <!-- Open Graph Meta-->
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Vali Admin">
    <meta property="og:title" content="Vali - Free Bootstrap 4 admin theme">
    <meta property="og:url" content="http://pratikborsadiya.in/blog/vali-admin">
    <meta property="og:image" content="http://pratikborsadiya.in/blog/vali-admin/hero-social.png">
    <meta property="og:description" content="Vali is a responsive and free admin theme built with Bootstrap 4, SASS and PUG.js. It's fully customizable and modular.">
    <title>Vali Admin - Free Bootstrap 4 Admin Template</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/main.css">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

   
</head>
<body class="app sidebar-mini rtl">
    <!-- Navbar-->
    <header class="app-header">
        <a class="app-header__logo" href="index.html">Delta</a>
        <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
        <!-- Navbar Right Menu-->
        <ul class="app-nav">
            <li class="app-search">
                <input class="app-search__input" type="search" placeholder="Search">
                <button class="app-search__button"><i class="fa fa-search"></i></button>
            </li>
            <!--Notification Menu-->
            <li class="dropdown">
                <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Show notifications"><i class="fa fa-bell-o fa-lg"></i></a>
                <ul class="app-notification dropdown-menu dropdown-menu-right">
                    <li class="app-notification__title">You have 4 new notifications.</li>
                    <div class="app-notification__content">
                    <li>
                        <a class="app-notification__item" href="javascript:;">
                            <span class="app-notification__icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span></span>
                            <div>
                                <p class="app-notification__message">Lisa sent you a mail</p>
                                <p class="app-notification__meta">2 min ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a class="app-notification__item" href="javascript:;">
                            <span class="app-notification__icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span></span>
                            <div>
                                <p class="app-notification__message">Mail server not working</p>
                                <p class="app-notification__meta">5 min ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a class="app-notification__item" href="javascript:;">
                            <span class="app-notification__icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span></span>
                            <div>
                                <p class="app-notification__message">Transaction complete</p>
                                <p class="app-notification__meta">2 days ago</p>
                            </div>
                        </a>
                    </li>
                    <div class="app-notification__content">
                    <li>
                        <a class="app-notification__item" href="javascript:;">
                            <span class="app-notification__icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-primary"></i><i class="fa fa-envelope fa-stack-1x fa-inverse"></i></span></span>
                            <div>
                                <p class="app-notification__message">Lisa sent you a mail</p>
                                <p class="app-notification__meta">2 min ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a class="app-notification__item" href="javascript:;">
                            <span class="app-notification__icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-danger"></i><i class="fa fa-hdd-o fa-stack-1x fa-inverse"></i></span></span>
                            <div>
                                <p class="app-notification__message">Mail server not working</p>
                                <p class="app-notification__meta">5 min ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a class="app-notification__item" href="javascript:;">
                            <span class="app-notification__icon"><span class="fa-stack fa-lg"><i class="fa fa-circle fa-stack-2x text-success"></i><i class="fa fa-money fa-stack-1x fa-inverse"></i></span></span>
                            <div>
                                <p class="app-notification__message">Transaction complete</p>
                                <p class="app-notification__meta">2 days ago</p>
                            </div>
                        </a>
                    </li>
                    </div>
                    </div>
                    <li class="app-notification__footer"><a href="#">See all notifications.</a></li>
                </ul>
            </li>
            <!-- User Menu-->
            <li class="dropdown">
                <a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
                <ul class="dropdown-menu settings-menu dropdown-menu-right">
                    <li><a class="dropdown-item" href="page-user.html"><i class="fa fa-cog fa-lg"></i> Settings</a></li>
                   <li><a class="dropdown-item" ><i class="fa fa-cog fa-lg"></i> registration</a></li>
                    <li><a class="dropdown-item" asp-area="Admin" asp-controller="Profile" asp-action="GET"><i class="fa fa-user fa-lg"></i> Profile</a></li>
                    <li><a class="dropdown-item" asp-area="Login" asp-controller="Registration" asp-action="Logout"><i class="fa fa-sign-out fa-lg"></i> Logout</a></li>
                </ul>
            </li>
        </ul>
    </header>

    <!-- Sidebar menu-->
    <div class="app-sidebar__overlay" data-toggle="sidebar"></div>
    <aside class="app-sidebar">
        <div class="app-sidebar__user">
            @*<img class="app-sidebar__user-avatar" src="https://s3.amazonaws.com/uifaces/faces/twitter/jsa/48.jpg" alt="User Image">*@
            <img class="app-sidebar__user-avatar" src="https://thumbs.dreamstime.com/z/unknown-male-avatar-profile-image-businessman-vector-unknown-male-avatar-profile-image-businessman-vector-profile-179373829.jpg?ct=jpeg" alt="User Image" height="80px">
            <div>
               
                
                <p class="app-sidebar__user-name">@ViewData["firstname"] @ViewData["lastname"]</p>
                <p class="app-sidebar__user-designation">frontend developer</p>
            </div>
        </div>
        <ul class="app-menu">
           
            <li><a class="app-menu__item active" asp-area="Admin" asp-controller="Dashboard" asp-action="GET"><i class="app-menu__icon fa fa-dashboard"></i><span class="app-menu__label">Dashboard</span></a></li>
           
            <li class="treeview">
                <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-th-list"></i><span class="app-menu__label">Tables</span><i class="treeview-indicator fa fa-angle-right"></i></a>
                <ul class="treeview-menu">
                    <li><a class="treeview-item" asp-area="Admin" asp-controller="Category" asp-action="GET"><i class="icon fa fa-circle-o"></i> Manage Category</a></li>
                    <li><a class="treeview-item" asp-area="Admin" asp-controller="SubCategory" asp-action="GET"><i class="icon fa fa-circle-o"></i> Manage Sucategory</a></li>
                    <li><a class="treeview-item" asp-area="Admin" asp-controller="Product" asp-action="GET"><i class="icon fa fa-circle-o"></i> Manage Product</a></li>
                    <li><a class="treeview-item" asp-area="Admin" asp-controller="AdminOrder" asp-action="GET"><i class="icon fa fa-circle-o"></i> Order</a></li>
                </ul>
            </li>
            
        </ul>
    </aside>


   
        <main class="app-content">
            @RenderBody()
        </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Supermarketsystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!-- Essential javascripts for application to work-->
    <script src="~/assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/main.js"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="~/assets/js/plugins/pace.min.js"></script>
    <!-- Page specific javascripts-->
    <script type="text/javascript" src="~/assets/js/plugins/chart.js"></script>
    <script type="text/javascript">
        var data = {
            labels: ["January", "February", "March", "April", "May"],
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(220,220,220,0.2)",
                    strokeColor: "rgba(220,220,220,1)",
                    pointColor: "rgba(220,220,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: [65, 59, 80, 81, 56]
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(151,187,205,0.2)",
                    strokeColor: "rgba(151,187,205,1)",
                    pointColor: "rgba(151,187,205,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: [28, 48, 40, 19, 86]
                }
            ]
        };
        var pdata = [
            {
                value: 300,
                color: "#46BFBD",
                highlight: "#5AD3D1",
                label: "Complete"
            },
            {
                value: 50,
                color: "#F7464A",
                highlight: "#FF5A5E",
                label: "In-Progress"
            }
        ]

        var ctxl = $("#lineChartDemo").get(0).getContext("2d");
        var lineChart = new Chart(ctxl).Line(data);

        var ctxp = $("#pieChartDemo").get(0).getContext("2d");
        var pieChart = new Chart(ctxp).Pie(pdata);
    </script>
    <!-- Google analytics script-->
    <script type="text/javascript">
        if (document.location.hostname == 'pratikborsadiya.in') {
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-72504830-1', 'auto');
            ga('send', 'pageview');
        }
    </script>

    <!-- Data table plugin-->
    <script type="text/javascript" src="~/assets/js/plugins/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/assets/js/plugins/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">$('#sampleTable').DataTable();</script>
    <!-- Google analytics script-->
    <script type="text/javascript">
        if (document.location.hostname == 'pratikborsadiya.in') {
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-72504830-1', 'auto');
            ga('send', 'pageview');
        }
    </script>

 


</body>
</html>

Supermarketsystem/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/main.css">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Login - Vali Admin</title>
</head>
<body>

    <section class="login-content">
        @RenderBody()
        </section>
    
    <!-- Essential javascripts for application to work-->
    <script src="~/assets/js/jquery-3.2.1.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/main.js"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="~/assets/js/plugins/pace.min.js"></script>
    <script type="text/javascript">
        // Login Page Flipbox control
        $('.login-content [data-toggle="flip"]').click(function () {
            $('.login-box').toggleClass('flipped');
            return false;
        });
    </script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>